/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estateicity;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jagan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
        
    private static final String username= "root";
    private static final String password= "kannan@mysqlroot";
    private static final String dataConn= "jdbc:mysql://localhost:3306/estate-icity";
        
    Connection sqlConn= null;
    PreparedStatement pst= null;    
    ResultSet rs= null;
    int q, i, id, deleteItem;
    
    public Login() {
        initComponents();
    }   
    
    //===========================================================================
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loginuname = new javax.swing.JLabel();
        loginupwd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginunamefield = new javax.swing.JTextField();
        loginpwdfield = new javax.swing.JPasswordField();
        loginback = new javax.swing.JButton();
        loginlogin = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel1.setText(" Login Page");

        loginuname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        loginuname.setText("Username:");

        loginupwd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        loginupwd.setText("Password:");

        loginunamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginunamefieldActionPerformed(evt);
            }
        });

        loginback.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        loginback.setText("Back");
        loginback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbackActionPerformed(evt);
            }
        });

        loginlogin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        loginlogin.setText("Login");
        loginlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel4))
                            .addComponent(loginuname)
                            .addComponent(loginupwd)
                            .addComponent(loginback))
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginunamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginpwdfield, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginlogin, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginuname)
                    .addComponent(loginunamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginupwd)
                    .addComponent(loginpwdfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginlogin)
                    .addComponent(loginback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginunamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginunamefieldActionPerformed
            // TODO add your handling code here:                
    }//GEN-LAST:event_loginunamefieldActionPerformed
    
    private JFrame frame;
    private void loginloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginloginActionPerformed
        // TODO add your handling code here:
         try{
            String uname = loginunamefield.getText();
            String pass = loginpwdfield.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            String query = "Select username,password from profile where username = '"+loginunamefield.getText()+"'";
            pst = sqlConn.prepareStatement(query);
            rs = pst.executeQuery();
            if(rs.next() && pass.equals(rs.getString("password"))){
                Lands hframe= new Lands();
                hframe.setVisible(true);
                this.dispose(); 
                
                JOptionPane.showMessageDialog(null, "Logged in!");                           
            }
            else{
                JOptionPane.showMessageDialog(null, "Login failed. Recheck credentials.");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
       
     }
     
    }//GEN-LAST:event_loginloginActionPerformed

    private void loginbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbackActionPerformed
        // TODO add your handling code here:
        Welcome hframe= new Welcome();
        hframe.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_loginbackActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton loginback;
    private javax.swing.JButton loginlogin;
    private javax.swing.JPasswordField loginpwdfield;
    private javax.swing.JLabel loginuname;
    private javax.swing.JTextField loginunamefield;
    private javax.swing.JLabel loginupwd;
    // End of variables declaration//GEN-END:variables
}
